const base = (name, slug, description, triggers, workflow, verificationRules, recovery, preferredTools = []) => ({
  id: `builtin:${slug}`, name, slug, description, scope: 'BUILTIN', version: 1, enabled: true,
  instructions: `${description}\nWorkflow: ${workflow.join(' → ')}.\nPrefer evidence over assumptions. Never bypass runtime safety, workspace boundaries, approval, or verification.`,
  metadata: { triggers, tags: triggers, capabilities: triggers, workflow, preferredTools, verificationRules, recovery, conflictsWith: [] }
})
export const BUILTIN_SKILLS = [
 base('Project Understanding','project-understanding','Map the project before changing it.',['understand','project','architecture','existing code'],['scan workspace','read package/config','identify conventions','summarize constraints'],['inspect relevant files before edit'],['re-scan after uncertainty'],['read_file','list_files']),
 base('Frontend Development','frontend-development','Build accessible, responsive user interfaces that fit the existing design system.',['react','frontend','ui','landing page','responsive','css'],['inspect components','implement small changes','check responsive states','verify build'],['build','visual/browser check','accessibility review'],['reduce to existing primitives and inspect console'],['read_file','write_file','run_command']),
 base('Debugging','debugging','Diagnose a reproducible failure before selecting a fix.',['debug','bug','error','broken','fix'],['reproduce','collect evidence','isolate cause','apply minimal fix','regress'],['reproduce failure','run targeted regression'],['revert hypothesis and gather new evidence'],['run_command','read_file']),
 base('Testing','testing','Create focused tests and use test output as delivery evidence.',['test','coverage','regression','unit test'],['identify behavior','add focused test','run target','run suite'],['targeted test','full relevant suite'],['minimize test and inspect fixture'],['run_command']),
 base('Browser QA','browser-qa','Validate user-facing workflows in a browser after implementation.',['browser','visual','qa','screenshot','responsive'],['start app','exercise workflow','inspect layout','record evidence'],['browser interaction','visual check'],['check console/network and narrow reproduction'],['browser_action']),
 base('Refactoring','refactoring','Improve structure without changing observable behavior.',['refactor','cleanup','restructure','duplicate'],['define invariants','make small mechanical edit','run regression','review diff'],['existing tests','diff review'],['rollback latest mechanical step'],['read_file','write_file','run_command']),
 base('Dependency Management','dependency-management','Change dependencies deliberately and verify lockfile/build impact.',['dependency','npm','package','install','upgrade'],['inspect manifest','check compatibility','change minimal set','build/test'],['lockfile consistency','build','tests'],['restore compatible version and explain constraint'],['read_file','run_command']),
 base('Git','git','Use version-control evidence and avoid destructive operations without approval.',['git','commit','branch','merge','diff'],['inspect status','review diff','make scoped change','verify status'],['git diff','git status'],['stop before destructive action and request approval'],['run_command'])
]
